# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce_text', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
